# -*- coding: utf-8 -*-
"""Chatbot Breast Health FAQ

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iCTcbaIHqBlzYHPbF06UgKItzzI3cAag
"""

import spacy

# Load the spaCy English language model
nlp = spacy.load("en_core_web_sm")

# Define responses
faq_responses = {
    "symptoms": "Common symptoms of breast cancer include a lump in the breast, changes in breast size or shape, nipple discharge, or skin changes such as dimpling.",
    "risk": "Risk factors for breast cancer include age, family history, genetic mutations (e.g., BRCA1, BRCA2), hormone replacement therapy, and certain lifestyle factors such as alcohol consumption and lack of physical activity.",
    "guidelines": "Screening guidelines for breast cancer recommend regular mammograms starting at age 40 for average-risk women. Women at higher risk may need to start screening earlier or undergo additional tests such as breast MRI.",
    "examination": "Breast self-examination involves checking your breasts regularly for any changes or abnormalities. This can be done through visual inspection and by feeling the breasts for lumps or other unusual signs.",
    "examine": "Breast self-examination involves checking your breasts regularly for any changes or abnormalities. This can be done through visual inspection and by feeling the breasts for lumps or other unusual signs.",
    "self": "Breast self-examination involves checking your breasts regularly for any changes or abnormalities. This can be done through visual inspection and by feeling the breasts for lumps or other unusual signs.",
    "preventions": "To reduce the risk of breast cancer, maintain a healthy lifestyle, limit alcohol consumption, avoid smoking, maintain a healthy weight, exercise regularly, and consider breastfeeding if possible.",
    "prevent": "To reduce the risk of breast cancer, maintain a healthy lifestyle, limit alcohol consumption, avoid smoking, maintain a healthy weight, exercise regularly, and consider breastfeeding if possible.",
    "treatment": "Treatment options for breast cancer depend on the stage of the cancer and may include surgery, radiation therapy, chemotherapy, hormone therapy, targeted therapy, or a combination of these treatments.",
    "treat": "Treatment options for breast cancer depend on the stage of the cancer and may include surgery, radiation therapy, chemotherapy, hormone therapy, targeted therapy, or a combination of these treatments.",
    "support": "There are various support resources available for individuals affected by breast cancer, including support groups, counseling services, online forums, and helplines. Your healthcare provider can also provide information and referrals to resources in your area.",
    "resources": "There are various support resources available for individuals affected by breast cancer, including support groups, counseling services, online forums, and helplines. Your healthcare provider can also provide information and referrals to resources in your area."
}

# Process user input
def respond_to_query(query):
    query_doc = nlp(query)
    matched_topics = [token.text.lower() for token in query_doc if token.text.lower() in faq_responses]
    if matched_topics:
        return faq_responses[matched_topics[0]]
    else:
        return "I'm sorry, I couldn't understand your question. Please try asking something else related to breast health."

# Interact with the user
def main():
    print("Welcome to the Breast Health Chatbot!")
    print("You can ask me questions about breast health, and I'll do my best to provide answers.")
    print("To exit, type 'quit'.")

    while True:
        user_input = input("You: ")
        if user_input.lower() == 'quit':
            print("Goodbye!")
            break
        response = respond_to_query(user_input)
        print("Bot:", response)

if __name__ == "__main__":
    main()